#
# TABLE STRUCTURE FOR: Job
#

DROP TABLE IF EXISTS `Job`;

CREATE TABLE `Job` (
  `Job` varchar(255) NOT NULL,
  `Pay` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `Job` (`Job`, `Pay`) VALUES ('LawnGreen', '842747');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('OliveDrab', '13741');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('RosyBrown', '46');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('Khaki', '801');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('Pink', '93547');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('LightPink', '97');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('LightSeaGreen', '5594');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('Brown', '9588597');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('Linen', '533');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('Moccasin', '12');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('GhostWhite', '4');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('SandyBrown', '15284');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('OrangeRed', '21695');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('Aqua', '8');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('LightGray', '747965241');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('Magenta', '88574');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('Cornsilk', '1406578');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('SlateGray', '393678');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('DarkBlue', '');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('Gray', '283');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('Magenta', '694487241');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('DarkSalmon', '9301400');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('AntiqueWhite', '23215322');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('LightCoral', '96653');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('Fuchsia', '7');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('SeaShell', '57257230');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('SkyBlue', '97');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('DarkBlue', '440884');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('Wheat', '52312537');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('Red', '');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('Aqua', '709');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('PeachPuff', '8977');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('FloralWhite', '10686724');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('DarkKhaki', '292963912');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('Cyan', '3');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('Gold', '682');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('LawnGreen', '894542600');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('MediumPurple', '264027');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('DarkSalmon', '3643221');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('DarkTurquoise', '269755');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('Bisque', '4134');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('Magenta', '914');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('Green', '382');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('LawnGreen', '90375686');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('PaleGoldenRod', '99255442');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('MediumAquaMarine', '100887');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('Chartreuse', '50834');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('MediumBlue', '31989831');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('Khaki', '');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('Lime', '408733');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('Green', '1737');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('Gold', '62689876');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('SlateBlue', '2');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('Purple', '9');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('DodgerBlue', '1588');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('Aquamarine', '389056');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('Green', '4379409');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('LightSteelBlue', '5809477');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('Aqua', '65940');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('Silver', '917587997');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('Orange', '342545665');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('LavenderBlush', '47777009');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('DarkRed', '95243');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('DarkBlue', '');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('NavajoWhite', '4');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('Indigo ', '3434829');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('DimGrey', '994864621');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('HotPink', '73242');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('DeepPink', '176');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('LightPink', '189');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('Linen', '8');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('PowderBlue', '38898235');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('Bisque', '48');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('Violet', '189330');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('Peru', '8533');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('PaleGreen', '77691989');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('LightSalmon', '7271');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('GoldenRod', '5912623');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('Chocolate', '');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('SeaShell', '71699557');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('MediumVioletRed', '68247');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('PaleVioletRed', '90');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('BlueViolet', '5254');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('LightSkyBlue', '');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('OldLace', '8');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('DarkGray', '85');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('Gold', '301883');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('Bisque', '2758');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('LavenderBlush', '79136177');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('DeepSkyBlue', '644219');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('Cornsilk', '94');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('LemonChiffon', '1013394');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('LightSalmon', '5786');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('PowderBlue', '9');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('DarkGray', '4153');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('Bisque', '8');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('MintCream', '61087');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('LightGreen', '83549664');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('Cyan', '448');
INSERT INTO `Job` (`Job`, `Pay`) VALUES ('Gray', '44');


#
# TABLE STRUCTURE FOR: Person
#

DROP TABLE IF EXISTS `Person`;

CREATE TABLE `Person` (
  `name` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `Person` (`name`) VALUES ('Myrtie Heaney');
INSERT INTO `Person` (`name`) VALUES ('Rosetta Kuhlman');
INSERT INTO `Person` (`name`) VALUES ('Maximus Spinka');
INSERT INTO `Person` (`name`) VALUES ('Donny Kulas');
INSERT INTO `Person` (`name`) VALUES ('Herman McGlynn');
INSERT INTO `Person` (`name`) VALUES ('Miss Lou Lesch PhD');
INSERT INTO `Person` (`name`) VALUES ('Mrs. Yasmeen Franecki');
INSERT INTO `Person` (`name`) VALUES ('Prof. Richard Steuber I');
INSERT INTO `Person` (`name`) VALUES ('Mrs. Miracle Bogan II');
INSERT INTO `Person` (`name`) VALUES ('Marta Harris');
INSERT INTO `Person` (`name`) VALUES ('Keon Corwin');
INSERT INTO `Person` (`name`) VALUES ('Braxton Stark');
INSERT INTO `Person` (`name`) VALUES ('Mr. Cristina Walter');
INSERT INTO `Person` (`name`) VALUES ('Cristal Schaefer');
INSERT INTO `Person` (`name`) VALUES ('Miss Melba Larson MD');
INSERT INTO `Person` (`name`) VALUES ('Darion Bernhard');
INSERT INTO `Person` (`name`) VALUES ('Jairo Frami');
INSERT INTO `Person` (`name`) VALUES ('Bridget Feil PhD');
INSERT INTO `Person` (`name`) VALUES ('Molly Gibson');
INSERT INTO `Person` (`name`) VALUES ('Kennedi Daniel');
INSERT INTO `Person` (`name`) VALUES ('Prof. Nicklaus Pollich IV');
INSERT INTO `Person` (`name`) VALUES ('Colin Luettgen DVM');
INSERT INTO `Person` (`name`) VALUES ('Boyd Rice I');
INSERT INTO `Person` (`name`) VALUES ('Eldred Kirlin III');
INSERT INTO `Person` (`name`) VALUES ('Garth Greenholt');
INSERT INTO `Person` (`name`) VALUES ('Laurel Spencer PhD');
INSERT INTO `Person` (`name`) VALUES ('Carley Schmidt');
INSERT INTO `Person` (`name`) VALUES ('Pearline Farrell');
INSERT INTO `Person` (`name`) VALUES ('Suzanne Carter DDS');
INSERT INTO `Person` (`name`) VALUES ('Claud Ziemann II');
INSERT INTO `Person` (`name`) VALUES ('Lee Baumbach');
INSERT INTO `Person` (`name`) VALUES ('Samir Nikolaus');
INSERT INTO `Person` (`name`) VALUES ('Prof. Burdette Dicki');
INSERT INTO `Person` (`name`) VALUES ('Prof. Carter Lindgren');
INSERT INTO `Person` (`name`) VALUES ('Holden Jones');
INSERT INTO `Person` (`name`) VALUES ('Karson Kassulke');
INSERT INTO `Person` (`name`) VALUES ('Eloy Spencer');
INSERT INTO `Person` (`name`) VALUES ('Onie Lind');
INSERT INTO `Person` (`name`) VALUES ('Pamela Gislason V');
INSERT INTO `Person` (`name`) VALUES ('Dr. Fae Bogan IV');
INSERT INTO `Person` (`name`) VALUES ('Dr. Rickie Gulgowski I');
INSERT INTO `Person` (`name`) VALUES ('Birdie Fisher');
INSERT INTO `Person` (`name`) VALUES ('Jules White');
INSERT INTO `Person` (`name`) VALUES ('Jerod Collier');
INSERT INTO `Person` (`name`) VALUES ('Eugene Hartmann');
INSERT INTO `Person` (`name`) VALUES ('Jensen Durgan');
INSERT INTO `Person` (`name`) VALUES ('Fernando McKenzie');
INSERT INTO `Person` (`name`) VALUES ('Dr. Vito Huel');
INSERT INTO `Person` (`name`) VALUES ('King Walter DVM');
INSERT INTO `Person` (`name`) VALUES ('Dayton Harber');
INSERT INTO `Person` (`name`) VALUES ('Buford Zulauf');
INSERT INTO `Person` (`name`) VALUES ('Eusebio Carroll');
INSERT INTO `Person` (`name`) VALUES ('Davonte Hermann');
INSERT INTO `Person` (`name`) VALUES ('Marian Ward');
INSERT INTO `Person` (`name`) VALUES ('Sarah Schinner');
INSERT INTO `Person` (`name`) VALUES ('Camila Connelly');
INSERT INTO `Person` (`name`) VALUES ('Dr. Kenyon Toy I');
INSERT INTO `Person` (`name`) VALUES ('Mr. Vicente Vandervort MD');
INSERT INTO `Person` (`name`) VALUES ('Jillian Stoltenberg');
INSERT INTO `Person` (`name`) VALUES ('Alisha Hilll');
INSERT INTO `Person` (`name`) VALUES ('Jarret Klocko');
INSERT INTO `Person` (`name`) VALUES ('Ola Lowe');
INSERT INTO `Person` (`name`) VALUES ('Margaretta Swaniawski');
INSERT INTO `Person` (`name`) VALUES ('Betty Durgan');
INSERT INTO `Person` (`name`) VALUES ('Dr. Reese Murray I');
INSERT INTO `Person` (`name`) VALUES ('Hilma Schaden');
INSERT INTO `Person` (`name`) VALUES ('Stephen Mraz MD');
INSERT INTO `Person` (`name`) VALUES ('Jedediah Leuschke I');
INSERT INTO `Person` (`name`) VALUES ('Malcolm Considine Sr.');
INSERT INTO `Person` (`name`) VALUES ('Mr. Xander Brekke Jr.');
INSERT INTO `Person` (`name`) VALUES ('Buck Steuber');
INSERT INTO `Person` (`name`) VALUES ('Kimberly Walker V');
INSERT INTO `Person` (`name`) VALUES ('Brant Lesch');
INSERT INTO `Person` (`name`) VALUES ('Cayla Bednar');
INSERT INTO `Person` (`name`) VALUES ('Mrs. Kiana Harvey V');
INSERT INTO `Person` (`name`) VALUES ('Manley Walker PhD');
INSERT INTO `Person` (`name`) VALUES ('Antonina Cole');
INSERT INTO `Person` (`name`) VALUES ('Dr. Keon Hirthe');
INSERT INTO `Person` (`name`) VALUES ('Prof. Lafayette Larkin II');
INSERT INTO `Person` (`name`) VALUES ('Oda Dietrich');
INSERT INTO `Person` (`name`) VALUES ('Sallie Simonis Sr.');
INSERT INTO `Person` (`name`) VALUES ('Brannon Frami');
INSERT INTO `Person` (`name`) VALUES ('Vernice Mertz');
INSERT INTO `Person` (`name`) VALUES ('Muhammad Donnelly');
INSERT INTO `Person` (`name`) VALUES ('Connor Ward');
INSERT INTO `Person` (`name`) VALUES ('Dr. Mauricio Block MD');
INSERT INTO `Person` (`name`) VALUES ('Maurice Marks');
INSERT INTO `Person` (`name`) VALUES ('Rebecca Medhurst');
INSERT INTO `Person` (`name`) VALUES ('Miss Antonietta McGlynn');
INSERT INTO `Person` (`name`) VALUES ('Weston Kovacek');
INSERT INTO `Person` (`name`) VALUES ('Mrs. Lila Wolff');
INSERT INTO `Person` (`name`) VALUES ('Elinor Predovic II');
INSERT INTO `Person` (`name`) VALUES ('Noel Haley DDS');
INSERT INTO `Person` (`name`) VALUES ('Branson Abshire');
INSERT INTO `Person` (`name`) VALUES ('Carlotta Hauck');
INSERT INTO `Person` (`name`) VALUES ('Darrell Wilderman');
INSERT INTO `Person` (`name`) VALUES ('Prof. Alexis Rodriguez');
INSERT INTO `Person` (`name`) VALUES ('Bertram Zboncak');
INSERT INTO `Person` (`name`) VALUES ('Irwin Streich DVM');
INSERT INTO `Person` (`name`) VALUES ('Vesta Schmidt II');


